
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List
href="Differences%20Between%20Tradermoni%20&amp;%20MarketMoni.fld/filelist.xml">
<style id="Differences Between Tradermoni &amp; MarketMoni_32585_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{mso-style-parent:style0;
	white-space:normal;}
.xl64
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;}
.xl65
	{mso-style-parent:style0;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl66
	{mso-style-parent:style0;
	font-weight:700;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;}
.xl67
	{mso-style-parent:style0;
	font-weight:700;
	text-align:center;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl68
	{mso-style-parent:style0;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl69
	{mso-style-parent:style0;
	font-weight:700;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl70
	{mso-style-parent:style0;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl71
	{mso-style-parent:style0;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl72
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:1.0pt solid windowtext;}
.xl73
	{mso-style-parent:style0;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl74
	{mso-style-parent:style0;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl75
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-align:center;
	border-top:1.0pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;}
.xl76
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-align:center;
	border-top:1.0pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
.xl77
	{mso-style-parent:style0;
	text-align:center;
	border-top:1.0pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
.xl78
	{mso-style-parent:style0;
	text-align:center;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Differences Between Tradermoni &amp; MarketMoni_32585" align=center
x:publishsource="Excel">

<table class='table table-striped table-responsive' border=0 cellpadding=0 cellspacing=0 width=1062 style='border-collapse:
 collapse;table-layout:fixed;width:796pt'>
 <col width=40 style='mso-width-source:userset;mso-width-alt:1280;width:30pt'>
 <col class=xl63 width=223 style='mso-width-source:userset;mso-width-alt:7125;
 width:167pt'>
 <col class=xl63 width=404 style='mso-width-source:userset;mso-width-alt:12928;
 width:303pt'>
 <col class=xl63 width=395 style='mso-width-source:userset;mso-width-alt:12629;
 width:296pt'>
 <tr height=21 style='height:16.0pt'>
  <td colspan=4 height=21 class=xl75 width=1062 style='border-right:1.0pt solid black;
  height:16.0pt;width:796pt'>DIFFERENCES BETWEEN TRADERMONI AND MARKETMONI</td>
 </tr>
 <tr height=21 style='height:16.0pt'>
  <td height=21 class=xl66 style='height:16.0pt;border-top:none'>S/N</td>
  <td class=xl67 width=223 style='border-top:none;border-left:none;width:167pt'>DESCRIPTION</td>
  <td class=xl67 width=404 style='border-top:none;border-left:none;width:303pt'>TRADERMONI</td>
  <td class=xl69 width=395 style='border-top:none;border-left:none;width:296pt'>MARKETMONI</td>
 </tr>
 <tr height=43 style='height:32.0pt'>
  <td height=43 class=xl64 style='height:32.0pt;border-top:none'>1</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Loan
  amount</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>10,000
  (first applicant), 15,000,20,000, 50,000 &amp; 100,000 naira.</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>10,000,
  20,000 &amp; 50,000(first applicant), 100,000 &amp; 250,000naira</td>
 </tr>
 <tr height=107 style='height:80.0pt'>
  <td height=107 class=xl64 style='height:80.0pt;border-top:none'>2</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Weekly
  payment amount</td>
  <td class=xl65 width=404 style='border-top:none;border-left:none;width:303pt'>Weekly
  payment of 860.00 naira for 3month, 430.00 naira for 6month</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>Weekly
  payment of 437.5 (for 10,000 naira)weekly payment of 875 naira (for 20,000
  naira)<span style='mso-spacerun:yes'>  </span>weekly payment of 2,187naira
  (for 50.000 naira loan), weekly payment of 4,375 naira (for 100,000 naira
  loan), weekly payment of 10.937 naira (for 250,000 naira loan).</td>
 </tr>
 <tr height=21 style='height:16.0pt'>
  <td height=21 class=xl64 style='height:16.0pt;border-top:none'>3</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Loan
  duration</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>24
  weeks</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>24
  weeks</td>
 </tr>
 <tr height=43 style='height:32.0pt'>
  <td height=43 class=xl64 style='height:32.0pt;border-top:none'>4</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Payment
  platform/Name of scheme for repayment</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>Interswitch
  Pay-Direct/BOI Geep</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>Interswitch
  Pay-Direct/BOI Geep Marketmoni</td>
 </tr>
 <tr height=21 style='height:16.0pt'>
  <td height=21 class=xl64 style='height:16.0pt;border-top:none'>5</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Admin.
  fee</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>2.5%
  on any loan amount</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>5%
  on any loan amount</td>
 </tr>
 <tr height=43 style='height:32.0pt'>
  <td height=43 class=xl64 style='height:32.0pt;border-top:none'>6</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Registration
  process</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>Through
  Enumerators or agents</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>Through
  BOI agents or Registered Association(apply.marketmoni.com.ng)</td>
 </tr>
 <tr height=21 style='height:16.0pt'>
  <td height=21 class=xl64 style='height:16.0pt;border-top:none'>7</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Grace
  period</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'>2
  weeks</td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>2
  weeks</td>
 </tr>
 <tr height=76 style='mso-height-source:userset;height:57.75pt'>
  <td height=76 class=xl64 style='height:57.75pt;border-top:none'>8</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>Beneficiary</td>
  <td class=xl65 width=404 style='border-top:none;border-left:none;width:303pt'>Small
  kiosk owner, food stuff seller, bread seller, mai shai, wheel barrow pusher,
  mobile tailor, mobile cobbler, fruits seller, keke rider.</td>
  <td class=xl74 width=395 style='border-top:none;border-left:none;width:296pt'>Market
  men and women, traders, artisans, enterprising youth, <br>
    small scale farmers and agricultural workers</td>
 </tr>
 <tr height=64 style='height:48.0pt'>
  <td height=64 class=xl64 style='height:48.0pt;border-top:none'>9</td>
  <td class=xl65 width=223 style='border-top:none;border-left:none;width:167pt'>List
  of Banks used for pay-direct.</td>
  <td class=xl68 width=404 style='border-top:none;border-left:none;width:303pt'><span
  style='mso-spacerun:yes'> </span>GTB, UBA, Ecobank, UnionBank, Stanbic IBTC,
  Sterling bank, Wema, Fidelity, Heritage, Jaiz.<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl70 width=395 style='border-top:none;border-left:none;width:296pt'>Gtbanks,
  Diamond bank, fidelity bank, Wema bank, Stanbic IBTC, Unity bank, Union bank,
  Jaiz bank, Sterling bank, Heritage bank, UBA, Eco bank.</td>
 </tr>
 <tr height=257 style='height:193.0pt'>
  <td height=257 class=xl72 style='height:193.0pt;border-top:none'>10</td>
  <td class=xl73 width=223 style='border-top:none;border-left:none;width:167pt'>Registration
  Requirement</td>
  <td class=xl73 width=404 style='border-top:none;border-left:none;width:303pt'>Registered
  phone number, capturing of applicant's face and goods.</td>
  <td class=xl71 width=395 style='border-top:none;border-left:none;width:296pt'>1.
  You must belong to a registered and accredited market association,
  cooperative <br>
    and trade group. <br>
    2. Customer/Beneficiary must be within the age range of<span
  style='mso-spacerun:yes'>  </span>18- 60 years. <br>
    3. You must have a valid Bank Verification Number (BVN). <br>
    4. Your market association, cooperative, or trade group must nominate you
  for a loan <br>
    and must be willing to stand in as your guarantor. <br>
    5. Your market association, cooperative or trade group must be registered
  with BOI. <br>
    </td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=40 style='width:30pt'></td>
  <td width=223 style='width:167pt'></td>
  <td width=404 style='width:303pt'></td>
  <td width=395 style='width:296pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
